### ISSUE TITLE
Schema problems in tests

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_openreferral#18]
I think @ekes hit some problems with schema so disabled strict schema checking for some tests.

Now we're getting the following: 
```
FILE: ...trib/localgov_openreferral/tests/src/Functional/ResourceTest.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 39 | ERROR | Do not disable strict config schema checking in tests.
    |       | Instead ensure your module properly declares its schema
    |       | for configurations.
----------------------------------------------------------------------
```

See https://github.com/localgovdrupal/localgov/runs/3721368822?check_suite_focus=true

**Comment by ekes** [comment]
Fixed with https://github.com/localgovdrupal/localgov_openreferral/commit/90e6444dbfab295bc2d4be1b12a2d41700a47713 and https://github.com/localgovdrupal/localgov/commit/63b29d7e2713e23ecd44b2062d02673f5c45ed53
