### ISSUE TITLE
Drupal 10 support 

### ISSUE THREAD

**Issue by stephen-cox** [localgovdrupal/localgov_openreferral#37]
Issue to track any changes needed to support Drupal 10

**Comment by stephen-cox** [comment]
Hi @ekes The tests for this fail on Drupal 10 and I don't really know where to start fixing them. Is this something you're able to look at?

**Comment by stephen-cox** [comment]
PR with failing tests #39

**Comment by finnlewis** [comment]
Closing this and we can open issues for specific bugs if/when needed.
