### ISSUE TITLE
OpenReferral: create a new site for openreferral testing.

### ISSUE THREAD

**Issue by finnlewis** [localgovdrupal/localgov_openreferral#5]
openreferral.localgovdrupal.org ?

**Comment by stephen-cox** [comment]
@willguv Can you please add the following DNS record for the new site:

CNAME record pointing openreferral.localgovdrupal.org to localgovdrupal.agile.coop

**Comment by finnlewis** [comment]
@willguv has requested this change with someone that supports the domain , hoping that this won't take too long. :)

**Comment by willguv** [comment]
Should be done now

**Comment by finnlewis** [comment]
Yup! 
http://openreferral.localgovdrupal.org/core/install.php

**Comment by finnlewis** [comment]
@ekes I think we can pass this to you to crack on with the site setup.  

Feel free to close this issue if all is done, or holler if you need something.

**Comment by ekes** [comment]
http://openreferral.localgovdrupal.org/openreferral/v1/services?page=1 for you full services wonder.
